### ISSUE TITLE
FlightSim

### ISSUE THREAD

**Issue by Luca0208** [Game-Fusion/MES#10]
Just two minor patches:
- make text at t he top white
- make screen white/black (black at the top, white at the bottom)

**Comment by Luca0208** [comment]
actually the text at the top needs to be black ofc

**Comment by Luca0208** [comment]
Fixed: http://pastebin.com/Q7L61A5V

**Comment by TheMrIron2** [comment]
Nice Luca, another game to add to MES! Keep it up!
