### ISSUE TITLE
[CCSand] Game will not boot

### ISSUE THREAD

**Issue by TheMrIron2** [Game-Fusion/MES#4]
CCSand is the only game to see through the wrapper and recognise the MES as a monochrome PC. Any fix for this would be a minor patch, however there would be theoretically a mountain of graphical glitches and the game is mouse reliant so a huge patch would be required if the game is to be released.

**Comment by byte-chan** [comment]
possible solution for the mouse problem:
- add keyboard controls for the mouse

**Comment by TheMrIron2** [comment]
That would be tricky - you could assign numbers to select a block/entity, but what about placing blocks on-screen? The only solution I can think of is using High or Low monochrome's cursor, where you use arrow keys to move a "mouse" on-screen and select something.

**Comment by byte-chan** [comment]
> arrow keys to move a "mouse" on-screen

THAT'S EXACTLY WHAT I MEAN

**Comment by TheMrIron2** [comment]
i misread it

**Comment by TheMrIron2** [comment]
Closed: This game has booted successfully since MonoColour wrapper 1.3, and this game's graphical errors are most likely impossible to solve using just two colours.
